version: '3'

services:
  redis-master:
    container_name: redis-master
    image: redis:4.0.2-alpine
    volumes:
      - "./data/redis-master:/data"
  redis-slave-1:
    container_name: redis-slave-1
    image: redis:4.0.2-alpine
    command: redis-server --slaveof redis-master 6379
    volumes:
      - "./data/redis-slave-1:/data"
    links:
      - redis-master   
  redis-slave-2:
    container_name: redis-slave-2
    image: redis:4.0.2-alpine
    command: redis-server --slaveof redis-master 6379
    volumes:
      - "./data/redis-slave-2:/data"
    links:
      - redis-master    
  redis-sentinel-1:
    container_name: redis-sentinel-1
    build: redis-sentinel
    links:
      - redis-master
  redis-sentinel-2:
    container_name: redis-sentinel-2
    build: redis-sentinel
    links:
      - redis-master
  redis-sentinel-3:
    container_name: redis-sentinel-3
    build: redis-sentinel
    links:
      - redis-master
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    links:
      - redis-master
    volumes:
      - "./data/redisinsight:/db"  
    ports:
      - "8001:8001" 
  client_node_app:
    container_name: client_node_app 
    build: client_node_app
    depends_on:
      - redis-sentinel-1 
      - redis-sentinel-2 
      - redis-sentinel-3  